spring:
  application:
    name: chatter-app
  datasource:
    url: jdbc:postgresql://localhost:5432/chatterdb
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true